Add language components
fork-commit-merge/fork-commit-merge-web pull request #193
Opened 2023-11-16 15:21 UTC by JonnyMc94

## Pull Request Type

What kind of change does this PR introduce?

[X] Feature

Issue Number: #191 

## What is the new behavior?

3 new languages have been added - Pony, Reason and PureScript.

## Does this introduce a breaking change?

[ ] Yes
[X] No

2023-11-16 22:17 UTC, JonnyMc94 commented
I have a few more I'd like to add so I if you could keep this open for a little bit that would be great!

2023-11-17 06:54 UTC, nikohoffren requested changes

2023-11-17 06:54 UTC, nikohoffren commented on components/languageComponents/PureScriptLanguage.tsx
> +          of PureScript's type classes also eliminates the need for many of the language
Everything looks good! However, i forgot to say that i have also ESLint set up in this project in the way that every `'` character has to be escaped using `&apos;` like in this example from the Dart language:

![apos-example](https://github.com/fork-commit-merge/fork-commit-merge-web/assets/82566656/9e45c42e-ec88-4642-9d37-98411ce1accb)

There you can see that the word `Google's` is changed to `Google&apos;s`. Otherwise the build in Vercel will fail.

2023-11-17 06:54 UTC, nikohoffren commented
> I have a few more I'd like to add so I if you could keep this open for a little bit that would be great!

> I have a few more I'd like to add so I if you could keep this open for a little bit that would be great!

Sure! Add as many as you like. Just tell me when you're ready to merge.

2023-11-18 16:49 UTC, nikohoffren approved these changes

2023-11-21 05:22 UTC, nikohoffren commented
> > I have a few more I'd like to add so I if you could keep this open for a little bit that would be great!
> 
> Sure! Add as many as you like. Just tell me when you're ready to merge.

Are you still going to add more commits to this PR? We usually close pull requests that are in idle for couple days or more to make the repository clean. If you're not adding anything else i can merge this.

2023-11-21 09:39 UTC, JonnyMc94 commented
> > > I have a few more I'd like to add so I if you could keep this open for a little bit that would be great!
> > 
> > 
> > Sure! Add as many as you like. Just tell me when you're ready to merge.
> 
> Are you still going to add more commits to this PR? We usually close pull requests that are in idle for couple days or more to keep the repository clean. If you're not adding anything else i can merge this.

I will add the last additions to this PR today, apologies for the delay

2023-11-21 11:38 UTC, JonnyMc94 commented
@nikohoffren those are the final changes I would like to include in this PR

2023-11-21 11:48 UTC, nikohoffren commented on components/languageComponents/VisualBasicLanguage.tsx
> +              - Insert one space between the comment delimiter (&apos) and the comment text.
This needs to be changed to `&apos;`

2023-11-21 11:48 UTC, nikohoffren commented on components/languageComponents/VisualBasicLanguage.tsx
> +            on forms, selections, and inputs. It&aposs also a popular choice for developing console
This needs to be changed to `&apos;`

2023-11-21 11:50 UTC, nikohoffren commented on components/languageComponents/VisualBasicLanguage.tsx
> +              - Do not use "My" or "my" as part of a variable name. This practice creates confusion
I also forgot to say that every `"` character needs to be replaced with `&quot;` so the Vercel deploy does not fail.

2023-11-21 11:52 UTC, nikohoffren requested changes
There are few of those `&apos;` and `&quot;` issues that i wrote as extra comments, that needs to be changed. Otherwise code looks good, and i can merge it when the issues are solved!

2023-11-21 12:15 UTC, merged

2023-11-21 12:15 UTC, nikohoffren commented
## Pull request merged

> This is an automated message from Fork, Commit, Merge - web [BOT].

Thank you for your contribution! Your pull request has been merged and your name has been added to the List of Contributors in README.md.
Please leave a star if you enjoyed working on this project.

### What's next?

If you're looking for more ways to contribute, I invite you to check out my other projects [here](https://github.com/nikohoffren?tab=repositories).