new language Gamemaker added
fork-commit-merge/fork-commit-merge-web pull request #210
Opened 2023-12-06 08:37 UTC by ruchikamuddinagiri

## Pull Request Type

What kind of change does this PR introduce?

[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:

## What is the current behavior?

The current Java logo is inaccurate and GameMaker language is missing in the Languages list.

Issue Number: [#174] 

## What is the new behavior?

We source our logos from the img.shields.io website, which uses icons from the the simple-icons repository. The Java logo currently points to the openjdk logo, which is available is the simple-icons repository. This logo cannot be replaced since the official Java logo does not exist in the simple-icons repository due to a copyright issue.

Relevant links:
https://github.com/simple-icons/simple-icons/issues/7374

## Does this introduce a breaking change?

[ ] Yes
[X] No

## Other information

2023-12-06 10:35 UTC, nikohoffren requested changes

2023-12-06 10:35 UTC, nikohoffren commented on components/languageComponents/GamemakerLanguage.tsx
> +          </p>
The `"` characters need to be escaped with `&quot;`, otherwise the Vercel build will fail. So you would have to change the `"write"` part to `&quot;write&quot;` to make this work. Other than that, the code looks good and i can merge it after the changes.

2023-12-06 18:27 UTC, ruchikamuddinagiri commented on components/languageComponents/GamemakerLanguage.tsx
> +          </p>
Thanks for bringing this to my attention, I've made the necessary changes.

2023-12-07 06:35 UTC, nikohoffren approved these changes
Looks good! Thanks for making the changes.

2023-12-07 06:35 UTC, merged